/*
 * Author: jianqing
 * Date: Dec 6, 2020
 * Description: This document is created for
 */
package bmcvocabtestgenerator;

import java.awt.datatransfer.StringSelection;
import java.io.IOException;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jianqing
 */
public class RegisterQuiz extends javax.swing.JFrame
{

    /**
     * Creates new form RegisterQuiz
     */
    public RegisterQuiz()
    {
        initComponents();
        generateQuizId();
        jPopupMenu1.add(generateIdMenuItem);
        jFormattedTextField1.setComponentPopupMenu(jPopupMenu1);
        aloneMode = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        generateIdMenuItem = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        quizNameField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        quizMessageField2 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        messageField = new javax.swing.JTextField();

        generateIdMenuItem.setText("Generate");
        generateIdMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                generateIdMenuItemActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(aloneMode?javax.swing.JFrame.EXIT_ON_CLOSE:javax.swing.JFrame.DISPOSE_ON_CLOSE);

        jLabel1.setText("Register Quiz");

        quizNameField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Quiz Name"));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Answers(Split by \",\")"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Document Link"));

        quizMessageField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Message"));

        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Quiz ID"));
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        messageField.setEditable(false);
        messageField.setText("Welcome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(messageField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quizNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(149, 149, 149))))
                    .addComponent(quizMessageField2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quizNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quizMessageField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        registerQuiz();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void generateIdMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_generateIdMenuItemActionPerformed
    {//GEN-HEADEREND:event_generateIdMenuItemActionPerformed
        // TODO add your handling code here:
        generateQuizId();
    }//GEN-LAST:event_generateIdMenuItemActionPerformed

    private void registerQuiz()
    {
        Thread t = new Thread(() ->
        {
            messageField.setText("Gathering information..");
            int quizId = Integer.parseInt(jFormattedTextField1.getText());
            String quizName, message, answers, link;
            quizName = quizNameField1.getText();
            message = quizMessageField2.getText();
            answers = jTextArea1.getText();
            link = jTextField1.getText();
            jButton1.setEnabled(false);

            messageField.setText("Connecting the server..");
            try (DatabaseConnector dbConn = DatabaseConnector.getDefaultInstance())
            {
                messageField.setText("Updating Quiz table..");
                dbConn.insertIntoQuizzes(new MyQuiz(quizId, link, null, message, 0, null));
                messageField.setText("Uploading answers");
                dbConn.insertIntoQuizAnswersGroup(answers.split(","), quizId);
                // insert if the quiz name is not empty
                if (!quizName.isEmpty())
                {
                    messageField.setText("Giving quiz an alias");
                    dbConn.insertIntoQuizId(quizId, quizName);
                }
                messageField.setText("Task Completed&link copied! question number: " + answers.split(",").length);
                getToolkit().getSystemClipboard().setContents(new StringSelection("https://85vocab.com/RequestQuizAnswer?id=" + (quizName.isEmpty() ? quizId : URLEncoder.encode(quizName, "UTF-8"))), null);
            } catch (Exception e)
            {
                messageField.setText("Failed to register your quiz!");
                Warning.createWarningDialog(e);
            }
            jButton1.setEnabled(true);

        });

        t.start();
    }

    private void generateQuizId()
    {
        try
        {
            jFormattedTextField1.setText(Integer.toString(RandomNumberGenerator.generateTrueRandomInteger(1, 9999, 100)[0]));
        } catch (IOException ex)
        {
            jFormattedTextField1.setText(Integer.toString(RandomNumberGenerator.randomInt(100, 9999)));
            Warning.createWarningDialog(ex);
            Logger.getLogger(RegisterQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean isAloneMode()
    {
        return aloneMode;
    }

    public void setAloneMode(boolean aloneMode)
    {
        this.aloneMode = aloneMode;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RegisterQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RegisterQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RegisterQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RegisterQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            RegisterQuiz rq = new RegisterQuiz();
            rq.setVisible(true);
            rq.setAloneMode(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem generateIdMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField messageField;
    private javax.swing.JTextField quizMessageField2;
    private javax.swing.JTextField quizNameField1;
    // End of variables declaration//GEN-END:variables
    private boolean aloneMode;
}
