/*
 * Author: jianqing
 * Date: Jun 20, 2020
 * Description: This document is created for
 */
package bmcvocabtestgenerator;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jianqing
 */
public class TestJFrame extends javax.swing.JFrame
{

    boolean cheating;
    String[] TABLE_HEADER = new String[]
    {
        "#", "Term", "#", "Term", "#", "Term", "#", "Term", "#", "Term", "#", "Term"
    };

    /**
     * Creates new form TestJFrame
     *
     * @param vocabulary
     */
    public TestJFrame(List<Vocabulary> vocabulary, int testId)
    {
        cheating=false;
        this.vocabList = vocabulary;
        this.testId = testId;
        preInit();
        initComponents();
        postInit();
    }

    
    public TestJFrame(Object[][] data, boolean cheating)
    {
        this.cheating=cheating;
        this.vocabList = new ArrayList<>();
        this.testId = 0;
        preInit();
        initComponents();
        postInit(data);
    }
    private void preInit()
    {

    }

    private void postInit()
    {
        loadTable();
    }

    private void postInit(Object[][] d)
    {
        if(cheating)
        {
            this.setBounds(this.getX(), this.getY(), this.getWidth()+600, this.getHeight());
        }
        loadTable(d);
        
    }
    private void loadTable()
    {

        Object[][] tableData = new Object[18/*This table has 18 rows*/][TABLE_HEADER.length];
        //tableData[row][column]

        for (int i = 0, id, row = 0, column = 0; i < vocabList.size(); i++, row++)
        {
            if (i % 17 == 0 && i != 0)
            {
                row = 0;//start to another big column
                column += 2;//shift the printing stream to right 2
            }
            id = i + 1;
            Vocabulary vocab = vocabList.get(i);
            System.out.println("row:" + row + " col: " + column);
            tableData[row][column] = id;
            tableData[row][column + 1] = vocab.getTerm();

        }
        loadTable(tableData);
    }

    public void loadTable(Object[][] data)
    {
        DefaultTableModel model = new DefaultTableModel(data, TABLE_HEADER);

        if(!cheating)
        {
            model.removeRow(17);
        }
        
        jTable1.setModel(model);

        if (jTable1.getColumnModel().getColumnCount() > 0)
        {
            int w = 35;
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(w);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(w);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(w);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(w);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(w);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(w);
        }
        
        if(cheating)
        {
            int w = 164;
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(w);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(w);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(w);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(w);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(w);
            jTable1.getColumnModel().getColumn(11).setPreferredWidth(w);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        viewAnswerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Your SAT Vocab Test");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "#", "Term", "#", "Term", "#", "Term", "#", "Term", "#", "Term", "#", "Term"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0)
        {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(35);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(35);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(35);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(35);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(35);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(35);
        }

        jLabel2.setText("Time Limit: 8min.");

        jLabel3.setText("Test Id:");

        jTextField1.setText(Integer.toString(testId)
        );

        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        viewAnswerButton.setText("View Answer");
        viewAnswerButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                viewAnswerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(219, 219, 219)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(viewAnswerButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(14, 14, 14)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(318, 318, 318))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(viewAnswerButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewAnswerButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_viewAnswerButtonActionPerformed
    {//GEN-HEADEREND:event_viewAnswerButtonActionPerformed
        try
        {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(new URI("https://85vocab.com"));
        } catch (URISyntaxException | IOException ex)
        {
            Warning.createWarningDialog(ex);
            Logger.getLogger(TestJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewAnswerButtonActionPerformed

    public JLabel getjLabel1()
    {
        return jLabel1;
    }

    public JButton getViewAnswerButton()
    {
        return viewAnswerButton;
    }

    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            //new TestJFrame().setVisible(true);
        });
    }

    private int testId;
    private List<Vocabulary> vocabList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton viewAnswerButton;
    // End of variables declaration//GEN-END:variables
}
